name: CI
on:
  push:
    tags:
      - "v*-staging*"
      - "v*-stable*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amanmemilih-frontend:${{ github.ref_name }}
          build-args: |
            NEXT_PUBLIC_API_URL=https://amanmemilih-backend.motionlaboratory.com

  deploy:
    runs-on: ubuntu-latest
    env:
      ARGOCD_SERVER: argocd.motionlaboratory.com
      ARGOCD_APP_NAME: amanmemilih-frontend
    needs: [build]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Update image with latest tags
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app set ${{ env.ARGOCD_APP_NAME }} --project amanmemilih-frontend-project --helm-set image.tag=${{ github.ref_name }}
          options: --auth-token=${{ secrets.ARGOCD_TOKEN_AWS }} --server=${{ env.ARGOCD_SERVER }}
      - name: Argo CD Action Sync
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app sync ${{ env.ARGOCD_APP_NAME }} --project amanmemilih-frontend-project
          options: --auth-token=${{ secrets.ARGOCD_TOKEN_AWS }} --server=${{ env.ARGOCD_SERVER }}
      - name: Argo CD Action Wait Healthy
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app wait ${{ env.ARGOCD_APP_NAME }} --grpc-web --health
          options: --auth-token=${{ secrets.ARGOCD_TOKEN_AWS }} --server=${{ env.ARGOCD_SERVER }}
